### ISSUE TITLE
Reviews

### ISSUE THREAD

**Issue by chawlapalak** [Shinh18/urltester#2]
Dear Muskan,

I reviewed your tool and found these issues:

1.  In the readMe file, you can fix these bugs:

- "Installation" is spelled wrong for heading.

-  In Installation, "local" has a typo error.

- You can add more steps for setting up the repository with clear instructions for review, as mentioned in Professor's [steps ](https://github.com/Seneca-CDOT/topics-in-open-source-2020/wiki/lab-1) like fork first and clone and then further steps.

- Features first line has a typo error in "The".

- "required" is spelled wrong.

- If you can add more information about the features, it would be more beneficial. For example: what arguments are passed etc.

2. In the code section, you can add comments for user readability. 

3. The tool is working. Congrats on the success! However, I would like to suggest to reduce the number of logs coming on the terminal for better user readability. It displays the whole stack trace on each request, which is failing; instead, it should be caught in a catch block with proper error messages.

**Comment by mshinh** [comment]
1. Solved the issue 0b13d564a143c4d385ff5237dd3e32d979290508
2. I will try to add more comments 
3. I will improve the catching of the error
