### ISSUE TITLE
improvements #1

### ISSUE THREAD

**Issue by PedroFonsecaDEV** [Shinh18/urltester#3]
-Add feature: request only headers.
-Add feature: fetch timeout.
-Propose of "-v" instead of "v"
-Better Formatting. (No callback hells)

Please let me know what do you think about these suggestions (the pull request is ready for you to merge).
I will wait for your feedback about it, so we can evaluate new PRs.  

Kind Regards.
Pedro

**Comment by mshinh** [comment]
I reviewed your suggestions and it makes my code better. 
I have merged your pull request 5f83591291d51f535100c64b70144ef1dc9beb50
Thanks for your help
