### ISSUE TITLE
Add lab 4 functionality

### ISSUE THREAD

**Issue by chawlapalak** [Shinh18/urltester#6]
Hi Muskan,
I would like to work on your repo for lab 4 functionalities. Let me know if you are okay with it?

**Comment by mshinh** [comment]
Sure. Thanks!

**Comment by chawlapalak** [comment]
Hi @Shinh18 

Please check the lab 4: ignore URL feature. You need to to add my fork as a remote, fetch, and test my branch i.e issue-6.
https://github.com/chawlapalak/urltester.git
Commit:  [bf4e7d3](https://github.com/chawlapalak/urltester/commit/bf4e7d3cf786e1d7a8af1c9a3e0f47bdf92cd151)
https://github.com/chawlapalak/urltester/tree/issue-6

Let me know if you need any changes. Thanks

**Comment by mshinh** [comment]
The added feature worked perfectly fine. 
I merged the branch with master. 
Thank you.
